### PR TITLE
2 Create the Send Message Page

### PR DESCRIPTION
**Pull request by L-Gu7**
https://github.com/agiledev-students-fall2022/final-project-team-stranger/issues/9

### CODE REVIEW

**Comment by RashedRifat** [comment]
LGTM!

**Comment by RashedRifat** [comment]
One small note - when performing input validation on the message component, it might be best to strip away some of the whitespaces before checking the data. Currently, if the user enters a newline character as input, it still counts as a message - we should think of a way to resolve this! 

A preliminary attempt may be using React's onSubmit attribute for the form - check if the data is appropriate at that point!

**Comment by L-Gu7** [comment]
> One small note - when performing input validation on the message component, it might be best to strip away some of the whitespaces before checking the data. Currently, if the user enters a newline character as input, it still counts as a message - we should think of a way to resolve this!
> 
> A preliminary attempt may be using React's onSubmit attribute for the form - check if the data is appropriate at that point!

I stripped the whitespaces before validating. It should work now.

**Review by RashedRifat — APPROVED** [review]
Looks good!

**Pull request merged**
